# Generated by Django 4.0.5 on 2022-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'AVAILABLE'), ('2', 'SOLD')], default=1, max_length=10),
        ),
    ]
