# Generated by Django 4.0.5 on 2022-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0004_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD')], default=1, max_length=10),
        ),
    ]
