# Generated by Django 4.0.5 on 2022-10-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0010_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='exchange',
            field=models.FloatField(choices=[(4.7878, 'EUR'), (4.896502352219268, 'USD'), (4.88053007135576, 'CHF'), (0.4374497478254513, 'SEK'), (1.0, 'PLN')], default='PLN'),
        ),
    ]
