# Generated by Django 4.0.5 on 2022-12-27 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0012_alter_calc_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calc',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calc',
            name='exchange',
            field=models.FloatField(choices=[(4.6423, 'EUR'), (4.3704575409527395, 'USD'), (4.704874835309617, 'CHF'), (0.41805574316718447, 'SEK'), (1, 'PLN')], default=1),
        ),
    ]
