# Generated by Django 4.0.5 on 2023-01-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0013_calc_date_posted_calc_title_alter_calc_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='exchange',
            field=models.FloatField(choices=[(4.695, 'EUR'), (4.378438869719295, 'USD'), (4.7385950746871215, 'CHF'), (0.4193349588703411, 'SEK'), (1, 'PLN')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD'), ('UNAVAILABLE', 'UNAVAILABLE'), ('IN PROGRESS', 'IN PROGRESS'), ('OTHER', 'OTHER')], default='AVAILABLE', max_length=12),
        ),
    ]
