# Generated by Django 4.0.5 on 2023-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0014_alter_calc_exchange_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='overall_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
