# Generated by Django 4.0.5 on 2023-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0015_calc_overall_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='exchange',
            field=models.FloatField(choices=[(4.71, 'EUR'), (4.350637354516904, 'USD'), (4.727966271832965, 'CHF'), (0.4218351171017868, 'SEK'), (1, 'PLN')], default=1),
        ),
        migrations.AlterField(
            model_name='calc',
            name='overall_price',
            field=models.FloatField(default=1),
        ),
    ]
