# Generated by Django 4.0.5 on 2023-01-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership_site', '0016_alter_calc_exchange_alter_calc_overall_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='calc',
            name='exchange',
            field=models.FloatField(choices=[(4.7113, 'EUR'), (4.333823935240548, 'USD'), (4.705183261759712, 'CHF'), (0.4237428383835658, 'SEK'), (1, 'PLN')], default=1),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership_site.post')),
            ],
        ),
    ]
